server:
  port: 8085

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/contact/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**, /api/categories/**, /api/publishers/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/borrow/**, /api/punishment/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
